k8s_namespace: "casopractico2"
directorio_trabajo: "/tmp"
azure_reg_user: crjuancasanueva
azure_reg_password: '9O8JGIEg9aY2PSZosHPqeZAPJuTlh/FHdKPaWRu+GT+ACRAkT3f4'
azure_reg: crjuancasanueva.azurecr.io
aplicacion:
  definicion: "statefull.yml"
  nombre: mongodb 
  imagen_original: docker.io/bitnami/mongodb:latest
  imagen: crjuancasanueva.azurecr.io/mongodb:casopractico2  
  replicas: 1
  recursos:
    cpu: 100m
    memoria: 128Mi
  limites:
    cpu: 250m
    memoria: 256Mi
  puerto: 27017