# Playbook para configurar una aplicación web de Apache en una máquina virtual de Azure, corriendo con Podman 
# y gestionado por systemd 
---
- name: 'Applicación Web en Maquina Virtual de Azure, con Podman y gestionado por systemd'
  hosts: vm
  remote_user: azureuser
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 'Instalar podman, skopeo, httpd-tools, openssl'
      become: true
      become_user: root
      become_method: sudo
      ansible.builtin.dnf:
        name: 
          - podman
          - skopeo
          - httpd-tools
          - openssl
        state: latest

    - name: 'Crear un directorio de trabajo'
      ansible.builtin.file:
        path: ./webserver
        state: directory

    - name: 'Instalar la libreria de python passlib'
      become: true
      become_user: root
      become_method: sudo
      ansible.builtin.pip:
        name: passlib

    - name: 'Crear el fichero de credenciales para la autenticación básica en el servidor Web.'
      community.general.htpasswd:
        path: ./webserver/.creds
        name: usertest
        password: 'test'

    - name: 'Crear clave privada para el certificado (2048 bits, RSA)'
      community.crypto.openssl_privatekey:
        path: ./webserver/localhost.key
        size: 2048

    - name: 'Crear la petición de firma del certificado'
      community.crypto.openssl_csr:
        path: ./webserver/localhost.csr
        privatekey_path: ./webserver/localhost.key
        country_name: ES
        state_or_province_name: Madrid
        locality_name: Madrid
        organization_name: DevOps
        organizational_unit_name: cp2
        common_name: vm1

    - name: 'Crear certificado utilizando la clave privada y la petición de firma'
      community.crypto.x509_certificate:
        path: ./webserver/localhost.crt
        privatekey_path: ./webserver/localhost.key
        csr_path: ./webserver/localhost.csr
        provider: selfsigned

    - name: 'Definir la página principal del servidor Web'
      ansible.builtin.copy:
        src: ./webserver_files/index.html
        dest: ./webserver/index.html

    - name: 'Definir la configuración del servidor Web'
      ansible.builtin.copy:
        src: ./webserver_files/httpd.conf
        dest: ./webserver/httpd.conf

    - name: 'Establecer la configuración de autenticación básica'
      ansible.builtin.copy:
        src: ./webserver_files/.htaccess
        dest: ./webserver/.htaccess

    - name: 'Definir el fichero para la creación de la imagen del contenedor'
      ansible.builtin.copy:
        src: ./webserver_files/Containerfile
        dest: ./webserver/Containerfile

    - name: 'Generar la imagen del contenedor'
      become: true
      become_user: root
      become_method: sudo
      containers.podman.podman_image:
        name: webserver
        path: ./webserver

    - name: 'Etiquetar la imagen del contenedor'
      become: true
      become_user: root
      become_method: sudo
      containers.podman.podman_tag:
        image: localhost/webserver:latest
        target_names:
          - "{{ webserver.imagen }}"

    - name: 'Autenticarse en el Registry de Azure'
      become: true
      become_user: root
      become_method: sudo
      containers.podman.podman_login:
        username: "{{ azure_reg_user }}"
        password: "{{ azure_reg_password }}"
        registry: "{{ azure_reg }}"

    - name: 'Subir la imagen del contenedor al Registry de Azure'
      become: true
      become_user: root
      become_method: sudo
      containers.podman.podman_image:
        name: "{{ webserver.imagen }}"
        push: yes
        push_args:
          dest: "{{ webserver.imagen }}"

    - name: 'Crear el contenedor del servicio Web a partir de la imagen en el Azure Registry'
      become: true
      become_user: root
      become_method: sudo
      containers.podman.podman_container:
        name: web
        image: "{{ webserver.imagen }}"
        state: created
        ports:
          - "8080:443"

    - name: 'Generar los ficheros para gestionar el contenedor a través de systemd'
      become: true
      become_user: root
      become_method: sudo
      containers.podman.podman_generate_systemd:
          name: web
          new: true
          dest: ./webserver

    - name: 'Copiar los ficheros generados en el paso previo al directorio de systemd'
      become: true
      become_user: root
      become_method: sudo
      ansible.builtin.copy:
        remote_src: true
        src: ./webserver/container-web.service
        dest: /etc/systemd/system/container-web.service

    - name: 'Recargar la configuración de systemd'
      become: true
      become_user: root
      become_method: sudo
      ansible.builtin.systemd:
        daemon_reload: true

    - name: 'Iniciar la aplicación Web desde systemd'
      become: true
      become_user: root
      become_method: sudo
      ansible.builtin.systemd:
        name: container-web.service
        enabled: true
        state: started

