# Playbook para desplegar un mongoDB en un cluster de AKS con almacenamiento persistente
---
- name: 'Applicación MongoDB corriendo en un cluster de aks con almacenamiendo persistente'
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 'Definir los objectos deployment, servicios, pvc, y pv'
      template:
        src: templates/statefull.j2
        dest: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"

    - name: 'Crear el namespace de trabajo'
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ k8s_namespace }}"

    - name: 'Crear Deployments y servicios de la aplicación'
      kubernetes.core.k8s:
        state: present
        template: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"