# Playbook para desplegar un mongoDB en un cluster de AKS con almacenamiento persistente
---
- name: 'Applicación MongoDB corriendo en un cluster de aks con almacenamiento persistente'
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 'Definir los objectos deployment, servicios, y pvc'
      template:
        src: templates/statefull.j2
        dest: "{{ aplicacion.directorio_trabajo }}/{{ aplicacion.definicion }}"
    
    - name: 'Instalar la libreria de python kubernetes'
      ansible.builtin.pip:
        name: kubernetes

    - name: 'Crear el namespace de trabajo en AKS'
      kubernetes.core.k8s:
        kubeconfig: "{{ aks_kube_config }}"
        context: "{{ aks_context }}"
        kind: Namespace
        name: "{{ k8s_namespace }}"

    - name: 'Crear Deployment, Service y PersistentVolumeClaim de la aplicación en AKS'
      kubernetes.core.k8s:
        kubeconfig: "{{ aks_kube_config }}"
        context: "{{ aks_context }}"
        state: present
        template: "{{ aplicacion.directorio_trabajo }}/{{ aplicacion.definicion }}"